site_name: Communication style guide
theme:
  name: material
  font: 
    text: Roboto
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content. tabs.link
    - content.code.annotation
    - content. code. copy
  language: en
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav: 
  - Communication fundamentals: 
    - Communication_fundamentals/index.md
    - Audience: Communication_fundamentals/Audience.md
    - Purpose: Communication_fundamentals/Purpose.md
    - Clarity: Communication_fundamentals/Clarity.md
    - Completeness: Communication_fundamentals/Completeness.md
    - Conciseness: Communication_fundamentals/Conciseness.md
    - Correctness: Communication_fundamentals/Correctness.md
    - Concreteness: Communication_fundamentals/Concreteness.md
    - Coherence: Communication_fundamentals/Coherence.md
    - Courtesy: Communication_fundamentals/Courtesy.md

copyright: 
  Copyright Sam Lee 2024